[project]
name = "finfo"
version = "1.0.0"
description = "Lightweight Python CLI script to quickly retrieve and inspect detailed information for files and folders."
requires-python = ">=3.12.0"
dependencies = [
  "chardet>=5.2.0",
  "mutagen>=1.47.0",
  "pefile>=2023.2.7",
  "Pillow>=10.0.0",
  "prompt_toolkit>=3.0.41",
  "pymediainfo>=6.1.0",
  "PyMuPDF>=1.23.0",
  "pywin32>=306; sys_platform == 'win32'",
  "regex>=2023.10.3",
  "typing-extensions>=4.6.0; python_version < '3.13'",
  "xulbux>=2.0.0",
]
optional-dependencies = { dev = [
  "coverage>=7.0.0",
  "freezegun>=1.5.5",
  "pyright>=1.1.408",
  "pytest>=7.4.2",
  "pytest-cov>=4.1.0",
  "pytest-mock>=3.12.0",
  "ruff>=0.9.0",
] }

[tool.coverage.report]
show_missing = true
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "raise NotImplementedError",
]

[tool.coverage.run]
branch = true
source = ["helpers", "finfo"]

[tool.pyright]
typeCheckingMode = "strict"
reportDeprecated = "warning"
reportPrivateUsage = "warning"
exclude = [
  "**/__pycache__",
  ".github",
  ".pytest_cache",
  ".pytest_tmp",
  ".ruff_cache",
  ".venv",
  "build",
]

[tool.pytest.ini_options]
addopts = "--basetemp=.pytest_temp --cov=helpers --cov=finfo --cov-report=term-missing -ra"
minversion = "7.0"
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
preview = true
line-length = 127
target-version = "py312"
extend-include = ["*.md"]

[tool.ruff.format]
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = [
  "B",   # flake8-bugbear (finds likely bugs & design problems)
  "C4",  # flake8-comprehensions (helps write better comprehensions)
  "C90", # mccabe complexity (checks cyclomatic complexity)
  "E",   # pycodestyle errors (checks PEP 8 style errors)
  "F",   # pyflakes (checks for logical errors)
  "I",   # isort (sorts imports)
  "RUF", # Ruff-specific linting rules
  "SIM", # flake8-simplify (helps simplify code)
  "TCH", # flake8-type-checking (manages type-checking imports)
  "UP",  # pyupgrade (upgrades syntax for newer Python versions)
  "W",   # pycodestyle warnings (checks PEP 8 style warnings)
]
ignore = ["ambiguous-unicode-character-docstring"]
mccabe = { max-complexity = 12 }

[tool.ruff.lint.isort]
split-on-trailing-comma = false
no-lines-before = ["first-party", "third-party"]
section-order = [
  "future",
  "local-folder",
  "standard-library",
  "first-party",
  "third-party",
]
